### ISSUE TITLE
Schema & MVPs

### ISSUE THREAD

**Issue by simcha-c** [vanduynamite/MuTube#1]
Hey Paul, 

Everything looks really great! I really do see the time that you put in here. Here are a few quick changes.

For the MVP's, make sure to have a title and detailed points about every MVP. The more detail you have in the bullet points, the better it will be for you. So, if you think of anything else that you might need in order to create a feature, you can add that as your bullet points.

Some things to change: 
1. Take a look at the email Matthias sent out about the MVP's. Basically, combine the upload videos and watch videos as one MVP. 
2. Split the comments and likes MVPs into two separate ones.
3. Put bonus features to a bonus section. ex. user show page with the videos that they've uploaded.

For the Schema:

4. When the column is a foreign key, just write foreign key. No need for the foreign key to be pointing to something.
5. I don't see anything in your MVP's that talk about showing how many views a video got. If that is a bonus MVP, then you should have that as a bonus table at the end.
6. For the likes table and the bonus tables, you would probably need some scoped uniqueness. A user can like a video once. A user can have one subscription.

Really good job!

**Comment by vanduynamite** [comment]
1. Combine upload and watch - done
2. Split comments and likes - done
3. Split out bonus features - done
4. Removed call outs to foreign key - done. For the bonus polymorphic likeable table, this info went into likeable_type instead.
5. Added views bonus MVP - done
6. Added scoped uniqueness where appropriate - done
