### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by simcha-c** [vanduynamite/MuTube#2]
1. On the videos table change the user_id to something more semantic. uploader_id?
2. On the likes table, what is the dislike column?
3. On the subscribers table, subscriber_id who is subscribing or who the user is subscribing to? Change user_id, and subscriber_id to clearer names.

Good job!

**Comment by vanduynamite** [comment]
1. uploader_id, done
2. Dislike is if someone gave it a thumbs down instead of thumbs up. Better
than an entirely new table?
3. Subscriber is the one who is subscribing. I changed user_id to
channel_id for you though.
