### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by simcha-c** [vanduynamite/MuTube#5]
- We actually don't have a sessions table. I might have told you to do that, but actually we need a session controller, and the user has that info on the users table. (like a04). sorry if i told you to do that. My bad.
- if there are columns that the scope of two columns is unique, mention that after the table instead of in the details of both columns. (ex. in the likes table)
- I see in the subscribers table, theres a channel_id? Thanks for changing it from user_id ;) but is channel_id the same as a user_id? or can a user create multiple channels? maybe channel_id isn't the correct wording for that?
- likes polymorphic looks great!

Really good job!

**Comment by vanduynamite** [comment]
1. I want a sessions table to allow the same user to log in on multiple devices.
2. I'll edit the scoped uniqueness as mentioned
3. Yes, it is the same as user_id. The actual YouTube does allow a user to create multiple channels but I think I will skip that part for my implementation. So a user has one channel. What do we do, channel_id, user_id, something_else_id?
4. Poly! Morphic!

**Comment by simcha-c** [comment]
The ability to allow users to login from multiple devices should be a bonus feature. Definitely something super cool to implement, but that is definitely bonus. 
channel_id sounds good then. You can always add multiple channels later on if you want to.
Great!

**Comment by vanduynamite** [comment]
Well it's already done sooooo
