### ISSUE TITLE
State

### ISSUE THREAD

**Issue by simcha-c** [vanduynamite/MuTube#6]
- user slice looks great!
- for the video slice: a user cant like and dislike a video, correct? so i really like the idea, but maybe we can instead have a key that says something like emotion: that can have values of 'like', 'dislike', or false? Maybe a different key to make it sound better... Otherwise, looks great!
- comments slice should have a parentCommentId and maybe same thing for likes/dislikes
- when you put the timeElapsed does that mean that your going to have to send an action every second? that might be too much... if we refresh the page, i guess the user will lose where they're at... too bad. :)

Everything else looks awesome! Really good job!

**Comment by vanduynamite** [comment]
1. Thanks!
2. I put in "user_emotion" as recommended
3. Yes I intended "parent_comment" to be "parent_comment_id". Has been changed, along with emotion.
4. Yeah that's a good observation. I'll take it out for now and as I learn about how it works we'll change it accordingly.

**Comment by simcha-c** [comment]
Thanks for these comments! I really like the communication! 👍
